# Generated by Django 5.0.1 on 2024-03-04 13:48

import MZI.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmzi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='adminmzi',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='adminmzi',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminmzi',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AddField(
            model_name='adminmzi',
            name='is_ok',
            field=models.BooleanField(default=True, verbose_name='آیا تایید شده است؟'),
        ),
        migrations.AddField(
            model_name='adminmzi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='adminmzi',
            name='id',
            field=models.CharField(default=MZI.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
    ]
