# Generated by Django 5.0.1 on 2024-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_adminmzi_created_at_adminmzi_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmzi',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='adminmzi',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='adminmzi',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profile_images/', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='adminmzi',
            name='role_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مسئولیت'),
        ),
    ]
