# Generated by Django 5.0.1 on 2024-02-19 05:12

import MZI.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(default=MZI.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی')),
                ('subject', models.CharField(blank=True, max_length=20, null=True, verbose_name='موضوع')),
                ('user_type', models.CharField(choices=[('گزینه 1', 'گزینه 1'), ('گزینه 2', 'گزینه 2'), ('گزینه 3', 'گزینه 3')], max_length=20, verbose_name='نوع کاربری')),
                ('priority', models.CharField(choices=[('کم', 'کم'), ('متوسط', 'متوسط'), ('زیاد', 'زیاد')], max_length=20, verbose_name='درجه اهمیت')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('additional_description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
