# Generated by Django 5.0.1 on 2024-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_rename_category_categoryarticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryarticle',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام دسته بندی'),
        ),
    ]
