# Generated by Django 5.0.1 on 2024-03-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل')),
                ('phone_prefix', models.CharField(blank=True, max_length=5, null=True, verbose_name='پیش\u200c شماره')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('working_days', models.CharField(blank=True, max_length=50, null=True, verbose_name='روزهای کاری')),
                ('whatsapp_mz', models.URLField(blank=True, null=True, verbose_name='آدرس واتساپ MZ')),
                ('linkedin_mz', models.URLField(blank=True, null=True, verbose_name='لینکدین MZ')),
                ('instagram_mz', models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام MZ')),
                ('telegram_mz', models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام MZ')),
                ('vichat_mz', models.URLField(blank=True, null=True, verbose_name='ویچت MZ')),
            ],
        ),
    ]
